### ISSUE TITLE
Not working on Ubuntu 18.04?

### ISSUE THREAD

**Issue by adrijere** [pwittchen/tmux-plugin-spotify#5]
Hi,

Thanks for this plugin. I installed it on my tmux and added that to my `~/.tmux.conf` file: 
```
set-option -g status-right "#{spotify_song}"
```

but nothing is shown on my tmux.
Did I miss something?

Thanks for your time

**Comment by pwittchen** [comment]
Have you satisfied project requirements: https://github.com/pwittchen/tmux-plugin-spotify#requirements ?

**Comment by adrijere** [comment]
Yes, spotify-cli-linux is installed and the PATH to `spotifycli` has been added to my PATH

**Comment by pwittchen** [comment]
Does spotifycli work on your computer? You can check it by executing e.g. `spotifycli --status`.

**Comment by adrijere** [comment]
It seems `spotifycli` was not well installed. Fixed with this: `sudo python3 -m pip install spotify-cli-linux`. Thanks for your help! :)
