### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by abhinavdhere** [pwittchen/tmux-plugin-spotify#6]
Thanks for building this utility. 
I'm not seeing anything on the status line after (I believe) following all instructions.

Environment: 
OS - Ubuntu 20.04
Shell - Bash
tmux - 3.0a

Installation & format strings - 
```

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-logging'
set -g @plugin 'tmux-plugins/tmux-online-status'
set -g @plugin 'pwittchen/tmux-plugin-spotify'

set -g status-right '#{spotify_song} | Internet: #{online_status} | #{battery_status_bg} Batt: #{battery_icon} #{battery_percentag    e} #{battery_remain} | %a %d-%h-%y %H:%M '
set -g status-right-length 100
set -g status-style fg=black,bold,bg=green
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

```
I am able to use spotifycli commands separately in the terminal.

**Comment by pwittchen** [comment]
Do you have Spotify turned on while using this plugin? It's necessary for
spotify-cli-linux program used by this plugin.

niedz., 3 sty 2021, 18:53 użytkownik Abhinav Dhere <notifications@github.com>
napisał:

**Comment by abhinavdhere** [comment]
Thanks for the response.
Yes, I have spotify running and I am getting expected output from calls like spotifycli --status.
However, nothing comes up on the status bar. I'll show a screenshot - 
![image](https://user-images.githubusercontent.com/11389893/103487786-e5c01e00-4e2d-11eb-878c-6eeb86454d4e.png)

**Comment by pwittchen** [comment]
That's strange. It should work. I'll have a closer look on that.

niedz., 3 sty 2021, 21:08 użytkownik Abhinav Dhere <notifications@github.com>
napisał:

**Comment by abhinavdhere** [comment]
It seems to be working today. I don't know what changed, seems to have resolved automatically!
Closing the issue but curious what might have happened here.
